name: e_sheet
description: A new Flutter project.


publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  flutter_bloc: ^8.1.1
  permission_handler: ^10.0.0
  bloc: ^8.1.0
  sqflite: ^2.1.0
  path:
  auto_size_text: ^3.0.0
  nearby_connections: ^3.2.0
  cupertino_icons: ^1.0.5
  build_runner: ^2.2.1
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0
  freezed: 2.1.0+1
  flutter_styled_toast: ^2.1.3
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.9
  syncfusion_flutter_xlsio: ^20.2.49-beta
  device_preview: ^1.1.0
  path_provider: ^2.0.11
  flutter_foreground_task: ^3.10.0
  excel: ^2.0.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/pics/app_icon.png

  android_12:
    image: assets/pics/app_icon.png
    icon_background_color: "#ffffff"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0



flutter:

  uses-material-design: true

  assets:
    - assets/pics/
    - assets/pics/home_background.png


  fonts:
    - family: RubikDistressed
      fonts:
        - asset: assets/fonts/RubikDistressed-Regular.ttf
          style: italic

    - family: KaushanScript
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf
          style: italic

    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf
          style: italic

